**Bankga mijozlarining qarzni qaytarish prognozi**

In [84]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [85]:
# Ma'lumotlarni yuklash
train_data = pd.read_csv('/content/train.csv')
test_data = pd.read_csv('/content/test.csv')
test_target = pd.read_csv('/content/sample_submission.csv')

In [86]:
train_data.head()

,id,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,0,15702656.0,Nwora,567.0,France,Male,33.0,9.0,0.0,2.0,1.0,0.0,156792.89,0.0
1,1,15647965.0,Yevdokimova,628.0,France,Female,38.0,3.0,0.0,1.0,1.0,1.0,51987.99,1.0
2,2,15798834.0,Ch'iu,635.0,France,Female,29.0,3.0,0.0,2.0,1.0,1.0,113079.19,0.0
3,3,15672056.0,Hsia,681.0,France,Male,28.0,6.0,0.0,2.0,1.0,0.0,14081.64,0.0
4,4,15759537.0,Okwudilichukwu,587.0,France,Female,27.0,5.0,0.0,2.0,1.0,0.0,158958.90,0.0

In [87]:
test_data.head()

,id,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,15000,15732563.0,Hs?,707.0,Germany,Male,21.0,4.0,114513.66,2.0,1.0,0.0,176692.87
1,15001,15727041.0,Ma,678.0,Germany,Male,33.0,5.0,142510.50,1.0,0.0,0.0,52820.13
2,15002,15753679.0,K?,636.0,Spain,Male,45.0,9.0,0.00,2.0,1.0,1.0,125062.02
3,15003,15581554.0,H?,697.0,Spain,Male,46.0,8.0,0.00,2.0,1.0,0.0,131647.41
4,15004,15773723.0,Bellucci,553.0,Spain,Male,31.0,2.0,0.00,2.0,1.0,0.0,58814.41

In [88]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               15000 non-null  int64
 1   CustomerId       15000 non-null  float64
 2   Surname          15000 non-null  object
 3   CreditScore      15000 non-null  float64
 4   Geography        15000 non-null  object
 5   Gender           15000 non-null  object
 6   Age              15000 non-null  float64
 7   Tenure           15000 non-null  float64
 8   Balance          15000 non-null  float64
 9   NumOfProducts    15000 non-null  float64
 10  HasCrCard        15000 non-null  float64
 11  IsActiveMember   15000 non-null  float64
 12  EstimatedSalary  15000 non-null  float64
 13  Exited           15000 non-null  float64
dtypes: float64(10), int64(1), object(3)
memory usage: 1.6+ MB

In [89]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               10000 non-null  int64
 1   CustomerId       10000 non-null  float64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  float64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  float64
 7   Tenure           10000 non-null  float64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  float64
 10  HasCrCard        10000 non-null  float64
 11  IsActiveMember   10000 non-null  float64
 12  EstimatedSalary  10000 non-null  float64
dtypes: float64(9), int64(1), object(3)
memory usage: 1015.8+ KB

In [90]:
encoder=LabelEncoder()
train_data['Geography']=encoder.fit_transform(train_data['Geography'].values)
train_data['Gender']=encoder.fit_transform(train_data['Gender'].values)
train_data['Surname']=encoder.fit_transform(train_data['Surname'].values)
test_data['Geography']=encoder.fit_transform(test_data['Geography'].values)
test_data['Gender']=encoder.fit_transform(test_data['Gender'].values)
test_data['Surname']=encoder.fit_transform(test_data['Surname'].values)

In [91]:
train_data.isnull().sum()

id                 0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [92]:
test_data.isnull().sum()

id                 0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
dtype: int64

In [93]:
features = ['CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'Balance',
            'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary']
X = train_data[features]
y = train_data['Exited']

In [94]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
test_data_scaled = scaler.transform(test_data[features])

In [95]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

In [98]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Model yaratish va o'qitish
model_lr = LogisticRegression(max_iter=1000, random_state=42)
model_lr.fit(X_train, y_train)

# Bashorat qilish
y_pred_lr = model_lr.predict(X_test)

# Aniqlikni baholash
accuracy_lr = accuracy_score(y_test, y_pred_lr)
print(f"Logistic Regression Model Accuracy: {accuracy_lr * 100:.2f}%")

Logistic Regression Model Accuracy: 87.00%

In [99]:
from sklearn.tree import DecisionTreeClassifier

# Model yaratish va o'qitish
model_dt = DecisionTreeClassifier(random_state=42)
model_dt.fit(X_train, y_train)

# Bashorat qilish
y_pred_dt = model_dt.predict(X_test)

# Aniqlikni baholash
accuracy_dt = accuracy_score(y_test, y_pred_dt)
print(f"Decision Tree Model Accuracy: {accuracy_dt * 100:.2f}%")

Decision Tree Model Accuracy: 84.23%

In [100]:
from sklearn.ensemble import RandomForestClassifier

# Model yaratish va o'qitish
model_rf = RandomForestClassifier(n_estimators=100, random_state=42)
model_rf.fit(X_train, y_train)

# Bashorat qilish
y_pred_rf = model_rf.predict(X_test)

# Aniqlikni baholash
accuracy_rf = accuracy_score(y_test, y_pred_rf)
print(f"Random Forest Model Accuracy: {accuracy_rf * 100:.2f}%")

Random Forest Model Accuracy: 89.27%

In [81]:
from sklearn.svm import SVC

# Model yaratish va o'qitish
model_svm = SVC(kernel='linear', random_state=42)
model_svm.fit(X_train, y_train)

# Bashorat qilish
y_pred_svm = model_svm.predict(X_test)

# Aniqlikni baholash
accuracy_svm = accuracy_score(y_test, y_pred_svm)
print(f"SVM Model Accuracy: {accuracy_svm * 100:.2f}%")

SVM Model Accuracy: 87.20%

In [101]:
from sklearn.neighbors import KNeighborsClassifier

# Model yaratish va o'qitish
model_knn = KNeighborsClassifier(n_neighbors=5)
model_knn.fit(X_train, y_train)

# Bashorat qilish
y_pred_knn = model_knn.predict(X_test)

# Aniqlikni baholash
accuracy_knn = accuracy_score(y_test, y_pred_knn)
print(f"KNN Model Accuracy: {accuracy_knn * 100:.2f}%")

KNN Model Accuracy: 87.63%

In [102]:
from sklearn.ensemble import GradientBoostingClassifier

# Model yaratish va o'qitish
model_gb = GradientBoostingClassifier(n_estimators=100, random_state=42)
model_gb.fit(X_train, y_train)

# Bashorat qilish
y_pred_gb = model_gb.predict(X_test)

# Aniqlikni baholash
accuracy_gb = accuracy_score(y_test, y_pred_gb)
print(f"Gradient Boosting Model Accuracy: {accuracy_gb * 100:.2f}%")

Gradient Boosting Model Accuracy: 89.97%